/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/space": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Space */
        get: operations["personal_space_api_v1_me_space_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items */
        get: operations["items_api_v1_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_v1_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Item */
        post: operations["copy_item_api_v1_items__item_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spaces */
        get: operations["spaces_api_v1_spaces_get"];
        put?: never;
        /** Create Space */
        post: operations["create_space_api_v1_spaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{space_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Space */
        delete: operations["delete_space_api_v1_spaces__space_id__delete"];
        options?: never;
        head?: never;
        /** Update Space */
        patch: operations["update_space_api_v1_spaces__space_id__patch"];
        trace?: never;
    };
    "/api/v1/spaces/{space_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_v1_spaces__space_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_spaces__space_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{space_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_spaces__space_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_v1_automation_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_automation_settings_patch"];
        trace?: never;
    };
    "/api/v1/automation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_automation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integrations */
        get: operations["integrations_api_v1_automation_integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/integrations/{integration_id}/destination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Destination */
        patch: operations["destination_api_v1_automation_integrations__integration_id__destination_patch"];
        trace?: never;
    };
    "/api/v1/automation/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_automation_events_get"];
        put?: never;
        /** Ingest */
        post: operations["ingest_api_v1_automation_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/events/{event_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_automation_events__event_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates */
        get: operations["candidates_api_v1_automation_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Candidate */
        patch: operations["edit_candidate_api_v1_automation_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/api/v1/automation/candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_v1_automation_candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_automation_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules */
        get: operations["rules_api_v1_automation_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_automation_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_automation_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_v1_automation_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/automation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_automation_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tick */
        post: operations["tick_api_v1_automation_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Read Notification */
        patch: operations["read_notification_api_v1_notifications__notification_id__read_patch"];
        trace?: never;
    };
    "/api/v1/automation/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_v1_automation_screenshots_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_automation_screenshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image */
        get: operations["image_api_v1_automation_screenshots__screenshot_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_api_v1_automation_screenshots__screenshot_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Result */
        post: operations["result_api_v1_automation_screenshots__screenshot_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Failure */
        post: operations["failure_api_v1_automation_screenshots__screenshot_id__failure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_automation_screenshots__screenshot_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_api_v1_automation_screenshots__screenshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/screenshots/{screenshot_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Text */
        patch: operations["correct_text_api_v1_automation_screenshots__screenshot_id__text_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            /**
             * Type
             * @enum {string}
             */
            type: "create_item" | "move_to_space" | "assign_user" | "set_type" | "set_deadline" | "create_notification" | "archive" | "ignore" | "complete_item";
            /** Value */
            value?: string | null;
            /**
             * Days Before
             * @default 0
             */
            days_before: number;
        };
        /** CalendarEntry */
        CalendarEntry: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            item: components["schemas"]["ItemOut"];
        };
        /** CalendarOut */
        CalendarOut: {
            /** Month */
            month: string;
            /** Entries */
            entries: components["schemas"]["CalendarEntry"][];
        };
        /** CandidateOut */
        CandidateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Inbound Event Id
             * Format: uuid
             */
            inbound_event_id: string;
            /** Candidate Index */
            candidate_index: number;
            /** Field Confidences */
            field_confidences: {
                [key: string]: components["schemas"]["FieldConfidence"];
            };
            /** Original Field Confidences */
            original_field_confidences: {
                [key: string]: components["schemas"]["FieldConfidence"];
            };
            /** Review Fields */
            review_fields?: string[];
            /**
             * Review Reason
             * @default
             */
            review_reason: string;
            /** Routing Source */
            routing_source: string;
            /** Routing Reason */
            routing_reason: string;
            /** Source Image Id */
            source_image_id?: string | null;
            /**
             * Suggested Space Id
             * Format: uuid
             */
            suggested_space_id: string;
            /** Suggested Assignee Id */
            suggested_assignee_id: string | null;
            payload: components["schemas"]["ItemFields-Output"];
            /** Original Payload */
            original_payload: {
                [key: string]: unknown;
            };
            /** Corrections */
            corrections: {
                [key: string]: unknown;
            }[];
            /** Confidence */
            confidence: number;
            /** Explanations */
            explanations: string[];
            /** Status */
            status: string;
            /** Item Id */
            item_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CandidatePatch */
        CandidatePatch: {
            fields?: components["schemas"]["ItemPatch"];
            /** Suggested Space Id */
            suggested_space_id?: string | null;
        };
        /** Condition */
        Condition: {
            /**
             * Field
             * @enum {string}
             */
            field: "source_type" | "sender" | "sender_domain" | "title" | "text" | "type" | "status" | "confidence" | "amount" | "space_id" | "delivery_status";
            /**
             * Operator
             * @enum {string}
             */
            operator: "equals" | "contains" | "greater_than" | "greater_or_equal" | "less_than";
            /** Value */
            value: string;
        };
        /** CopyInput */
        CopyInput: {
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "KRW" | "USD" | "JPY" | "EUR" | "GBP" | "CNY";
        /** DashboardOut */
        DashboardOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Inbox Count */
            inbox_count: number;
            /** Overdue Count */
            overdue_count: number;
            /** Week Deadline Count */
            week_deadline_count: number;
            /** Today Count */
            today_count: number;
            /** Today Items */
            today_items: components["schemas"]["ItemOut"][];
            /** Overdue Items */
            overdue_items: components["schemas"]["ItemOut"][];
            /** Payments */
            payments: {
                [key: string]: string;
            };
            /** Payment Missing Amount Count */
            payment_missing_amount_count: number;
        };
        /** EventOut */
        EventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Type */
            source_type: string;
            /** External Id */
            external_id: string;
            /** Raw Content */
            raw_content: {
                [key: string]: unknown;
            };
            /** Normalized Content */
            normalized_content: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Processed At */
            processed_at: string | null;
        };
        /** FieldConfidence */
        FieldConfidence: {
            /** Value */
            value: string | number | boolean | null;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationDestination */
        IntegrationDestination: {
            /** Space Id */
            space_id?: string | null;
        };
        /** IntegrationOut */
        IntegrationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Default Space Id */
            default_space_id: string | null;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default other */
            type: components["schemas"]["ItemType"];
            /** Deadline */
            deadline?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** Amount */
            amount?: string | null;
            /** @default KRW */
            currency: components["schemas"]["Currency"];
            /**
             * Source Text
             * @default
             */
            source_text: string;
            /** Space Id */
            space_id?: string | null;
        };
        /** ItemFields */
        "ItemFields-Input": {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default other */
            type: components["schemas"]["ItemType"];
            /** Deadline */
            deadline?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** Amount */
            amount?: string | null;
            /** @default KRW */
            currency: components["schemas"]["Currency"];
        };
        /** ItemFields */
        "ItemFields-Output": {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default other */
            type: components["schemas"]["ItemType"];
            /** Deadline */
            deadline?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** Amount */
            amount?: string | null;
            /** @default KRW */
            currency: components["schemas"]["Currency"];
        };
        /** ItemOut */
        ItemOut: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default other */
            type: components["schemas"]["ItemType"];
            /** Deadline */
            deadline?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** Amount */
            amount?: string | null;
            /** @default KRW */
            currency: components["schemas"]["Currency"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Space Id
             * Format: uuid
             */
            space_id: string;
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            status: components["schemas"]["Status"];
            /** Source Type */
            source_type: string;
            /** Source Text */
            source_text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Assignee Id */
            assignee_id?: string | null;
        };
        /** ItemPage */
        ItemPage: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ItemPatch */
        ItemPatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            type?: components["schemas"]["ItemType"] | null;
            status?: components["schemas"]["Status"] | null;
            /** Deadline */
            deadline?: string | null;
            /** Start Datetime */
            start_datetime?: string | null;
            /** End Datetime */
            end_datetime?: string | null;
            /** Amount */
            amount?: string | null;
            currency?: components["schemas"]["Currency"] | null;
            /** Space Id */
            space_id?: string | null;
        };
        /**
         * ItemType
         * @enum {string}
         */
        ItemType: "task" | "deadline" | "event" | "reservation" | "payment" | "delivery" | "purchase" | "return" | "document" | "note" | "other";
        /** MemberInput */
        MemberInput: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "member" | "viewer";
        };
        /** MemberOut */
        MemberOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Role */
            role: string;
        };
        /** NotificationOut */
        NotificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Id */
            item_id: string | null;
            /** Rule Id */
            rule_id: string | null;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Status */
            status: string;
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RuleInput */
        RuleInput: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Space Id */
            space_id?: string | null;
            /** Scope Type */
            scope_type?: ("global" | "space" | "integration") | null;
            /** Scope Id */
            scope_id?: string | null;
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /**
             * Trigger Type
             * @enum {string}
             */
            trigger_type: "inbound_received" | "candidate_created" | "item_created" | "item_updated" | "deadline_approaching" | "integration_sync";
            /** Conditions */
            conditions?: components["schemas"]["Condition"][];
            /** Actions */
            actions: components["schemas"]["Action"][];
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
        };
        /** RuleOut */
        RuleOut: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Space Id */
            space_id?: string | null;
            /** Scope Type */
            scope_type?: ("global" | "space" | "integration") | null;
            /** Scope Id */
            scope_id?: string | null;
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /**
             * Trigger Type
             * @enum {string}
             */
            trigger_type: "inbound_received" | "candidate_created" | "item_created" | "item_updated" | "deadline_approaching" | "integration_sync";
            /** Conditions */
            conditions?: components["schemas"]["Condition"][];
            /** Actions */
            actions: components["schemas"]["Action"][];
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Id */
            rule_id: string | null;
            /** Rule Name */
            rule_name: string;
            /** Trigger Type */
            trigger_type: string;
            /**
             * Trigger Entity Id
             * Format: uuid
             */
            trigger_entity_id: string;
            /** Status */
            status: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: unknown;
            };
            /** Output Snapshot */
            output_snapshot: {
                [key: string]: unknown;
            };
            /** Error Message */
            error_message: string | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
        };
        /** ScreenshotClaim */
        ScreenshotClaim: {
            /**
             * Claim Token
             * Format: uuid
             */
            claim_token: string;
        };
        /** ScreenshotFailure */
        ScreenshotFailure: {
            /**
             * Claim Token
             * Format: uuid
             */
            claim_token: string;
        };
        /** ScreenshotOut */
        ScreenshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Inbound Event Id
             * Format: uuid
             */
            inbound_event_id: string;
            /** File Name */
            file_name: string;
            /** Mime Type */
            mime_type: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Ocr Status */
            ocr_status: string;
            /** Ocr Text */
            ocr_text: string | null;
            /** Ocr Confidence */
            ocr_confidence: number | null;
            /** Provider */
            provider: string | null;
            /** Error Message */
            error_message: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at: string | null;
        };
        /** ScreenshotPage */
        ScreenshotPage: {
            /** Provider */
            provider: string;
            /** Inputs */
            inputs: components["schemas"]["ScreenshotOut"][];
        };
        /** ScreenshotResult */
        ScreenshotResult: {
            /**
             * Claim Token
             * Format: uuid
             */
            claim_token: string;
            /** Text */
            text: string;
            /** Confidence */
            confidence: number;
        };
        /** ScreenshotText */
        ScreenshotText: {
            /** Text */
            text: string;
        };
        /** SettingsInput */
        SettingsInput: {
            /**
             * Level
             * @default suggest
             * @enum {string}
             */
            level: "suggest" | "auto_capture" | "auto_action";
            /**
             * Capture Threshold
             * @default 0.95
             */
            capture_threshold: number;
            /**
             * Review Threshold
             * @default 0.7
             */
            review_threshold: number;
        };
        /** ShareInput */
        ShareInput: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Content */
            content: string;
            /**
             * Source Type
             * @default manual_share
             * @enum {string}
             */
            source_type: "manual_share" | "email" | "calendar" | "webhook" | "screenshot";
            /**
             * Sender
             * @default
             */
            sender: string;
            /** External Id */
            external_id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            fields?: components["schemas"]["ItemFields-Input"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** SpaceCreate */
        SpaceCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default personal
             * @enum {string}
             */
            type: "personal" | "shared";
        };
        /** SpaceOut */
        SpaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Role
             * @default owner
             */
            role: string;
        };
        /** SpacePatch */
        SpacePatch: {
            /** Name */
            name?: string | null;
            /** Is Default */
            is_default?: true | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "inbox" | "todo" | "in_progress" | "completed" | "archived";
        /** SummaryOut */
        SummaryOut: {
            /** Active Rules */
            active_rules: number;
            /** Today Processed */
            today_processed: number;
            /** Review Count */
            review_count: number;
            /** Failed Count */
            failed_count: number;
            /** Unread Notifications */
            unread_notifications: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    personal_space_api_v1_me_space_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
        };
    };
    items_api_v1_items_get: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["Status"] | null;
                type?: components["schemas"]["ItemType"] | null;
                page?: number;
                page_size?: number;
                space_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                space_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_v1_calendar_get: {
        parameters: {
            query: {
                month: string;
                space_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_item_api_v1_items__item_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spaces_api_v1_spaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"][];
                };
            };
        };
    };
    create_space_api_v1_spaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_space_api_v1_spaces__space_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_space_api_v1_spaces__space_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_v1_spaces__space_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_spaces__space_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_spaces__space_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_v1_automation_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsInput"];
                };
            };
        };
    };
    update_settings_api_v1_automation_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsInput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_automation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    integrations_api_v1_automation_integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationOut"][];
                };
            };
        };
    };
    destination_api_v1_automation_integrations__integration_id__destination_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationDestination"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_automation_events_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_v1_automation_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_automation_events__event_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_api_v1_automation_candidates_get: {
        parameters: {
            query?: {
                page?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_candidate_api_v1_automation_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_v1_automation_candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_automation_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_api_v1_automation_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    create_rule_api_v1_automation_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_automation_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_automation_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_automation_runs_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tick_api_v1_automation_tick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_notification_api_v1_notifications__notification_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_v1_automation_screenshots_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_automation_screenshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotOut"];
                };
            };
        };
    };
    image_api_v1_automation_screenshots__screenshot_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_api_v1_automation_screenshots__screenshot_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotClaim"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_v1_automation_screenshots__screenshot_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenshotResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    failure_api_v1_automation_screenshots__screenshot_id__failure_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenshotFailure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_automation_screenshots__screenshot_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_v1_automation_screenshots__screenshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_text_api_v1_automation_screenshots__screenshot_id__text_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenshotText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
