import { PGlite } from "@electric-sql/pglite";
import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";

const db = await PGlite.create();
const a = "11111111-1111-4111-8111-111111111111", b = "22222222-2222-4222-8222-222222222222";
try {
  await db.exec("CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY, raw_user_meta_data jsonb DEFAULT '{}');");
  const migrationFile = process.argv[2] || new URL("../apps/api/migrations/versions/0001_initial.sql", import.meta.url);
  await db.exec((await readFile(migrationFile, "utf8")).replace(/^\uFEFF/, ""));
  if (process.argv[2]) assert.equal((await db.query("SELECT version_num FROM app_migrations.alembic_version")).rows[0].version_num, "0001");
  await db.query("INSERT INTO auth.users(id,raw_user_meta_data) VALUES($1,'{\"display_name\":\"테스트 A\"}'),($2,'{}')", [a, b]);
  const spaces = (await db.query("SELECT id,owner_id FROM app.spaces ORDER BY owner_id")).rows;
  assert.equal(spaces.length, 2);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.space_members WHERE role='owner'")).rows[0].n, 2);
  await assert.rejects(db.query("INSERT INTO app.spaces(name,type,owner_id) VALUES('duplicate','personal',$1)", [a]), /duplicate key/);
  const ai = (await db.query("INSERT INTO app.items(space_id,creator_id,title,source_text) VALUES($1,$2,'이어폰 반품','원문') RETURNING id", [spaces[0].id, a])).rows[0].id;
  await db.query("INSERT INTO app.items(space_id,creator_id,title) VALUES($1,$2,'다른 사용자 항목')", [spaces[1].id, b]);
  await db.query("INSERT INTO app.item_updates(item_id,user_id,type,content) VALUES($1,$2,'comment','비공개 update')", [ai, a]);
  await db.query("INSERT INTO app.attachments(item_id,uploaded_by,file_name,mime_type,size_bytes,storage_bucket,storage_path) VALUES($1,$2,'영수증.pdf','application/pdf',100,'files','a.pdf')", [ai, a]);
  await db.exec("SET ROLE lifeinbox_app");
  assert.equal((await db.query("SELECT count(*)::int n FROM app.items")).rows[0].n, 0);
  await db.exec("BEGIN");
  await db.query("SELECT set_config('app.user_id',$1,true)", [a]);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.items")).rows[0].n, 1);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.users")).rows[0].n, 1);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.item_updates")).rows[0].n, 1);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.attachments")).rows[0].n, 1);
  assert.equal((await db.query("SELECT title FROM app.items WHERE title ILIKE '%이어폰%'")).rows[0].title, "이어폰 반품");
  await db.query("UPDATE app.items SET title='수정된 제목' WHERE id=$1", [ai]);
  await db.exec("COMMIT");
  assert.equal((await db.query("SELECT count(*)::int n FROM app.items")).rows[0].n, 0);
  await db.exec("BEGIN");
  await db.query("SELECT set_config('app.user_id',$1,true)", [b]);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.items")).rows[0].n, 1);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.attachments")).rows[0].n, 0);
  assert.equal((await db.query("UPDATE app.items SET title='위조' WHERE id=$1 RETURNING id", [ai])).rows.length, 0);
  assert.equal((await db.query("DELETE FROM app.items WHERE id=$1 RETURNING id", [ai])).rows.length, 0);
  await db.exec("ROLLBACK");
  await assert.rejects(db.query("INSERT INTO app.items(space_id,creator_id,title) VALUES($1,$2,'위조')", [spaces[0].id, b]), /row-level security/);
  await assert.rejects(db.query("INSERT INTO app.spaces(name,type,owner_id) VALUES('위조','personal',$1)", [b]), /permission denied/);
  await db.exec("RESET ROLE");
  await assert.rejects(db.query("UPDATE app.items SET assignee_id=$1 WHERE id=$2", [b, ai]), /foreign key/);
  await assert.rejects(db.query("UPDATE app.items SET amount=1.25,currency='KRW' WHERE id=$1", [ai]), /check constraint/);
  await assert.rejects(db.query("UPDATE app.items SET end_datetime='2026-10-05' WHERE id=$1", [ai]), /check constraint/);
  await db.query("DELETE FROM app.items WHERE id=$1", [ai]);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.attachments")).rows[0].n, 0);
  assert.equal((await db.query("SELECT count(*)::int n FROM app.item_updates")).rows[0].n, 0);
  console.log("DB checks passed: signup, uniqueness, RLS, transaction isolation, Korean search, constraints, cascades.");
} finally { await db.close(); }
